// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz9CEhzsGhMIIErQOpwn3f9DeeS-_rcHM',
    appId: '1:756775121593:web:f976eb2367d064f9e4a168',
    messagingSenderId: '756775121593',
    projectId: 'walletview-c510c',
    authDomain: 'walletview-c510c.firebaseapp.com',
    storageBucket: 'walletview-c510c.appspot.com',
    measurementId: 'G-BZ7RGMFG2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpdQPlH2_MOwoqbcjYQi6Da2Aiwb6L_DA',
    appId: '1:756775121593:android:0531d545454297dde4a168',
    messagingSenderId: '756775121593',
    projectId: 'walletview-c510c',
    storageBucket: 'walletview-c510c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqGO58WssYxOXCbIBYHZPWSk73LhSlPr0',
    appId: '1:756775121593:ios:fc675ab1c048255de4a168',
    messagingSenderId: '756775121593',
    projectId: 'walletview-c510c',
    storageBucket: 'walletview-c510c.appspot.com',
    iosBundleId: 'com.example.walletView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqGO58WssYxOXCbIBYHZPWSk73LhSlPr0',
    appId: '1:756775121593:ios:fc675ab1c048255de4a168',
    messagingSenderId: '756775121593',
    projectId: 'walletview-c510c',
    storageBucket: 'walletview-c510c.appspot.com',
    iosBundleId: 'com.example.walletView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz9CEhzsGhMIIErQOpwn3f9DeeS-_rcHM',
    appId: '1:756775121593:web:1c0afb9f06ab0c66e4a168',
    messagingSenderId: '756775121593',
    projectId: 'walletview-c510c',
    authDomain: 'walletview-c510c.firebaseapp.com',
    storageBucket: 'walletview-c510c.appspot.com',
    measurementId: 'G-TEQG676R84',
  );
}
